apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  serviceName: memcached
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: memcached
        image: memcached:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 11211
          name: intra-node
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
           cpu: "500m"
           memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  clusterIP: None
  ports:
  - port: 11211
  selector:
    app: memcached
